apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- include "mychart.systemlables" $ | indent 2 }}
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  zone: {{ quote .Values.infra.zone }}
  region: {{ lower .Values.infra.region }}
  projectCode: {{ upper .Values.projectCode }}
  now: {{ now | date "2006-01-02" | quote }}
  pipeline: {{ .Values.projectCode | upper | quote }}
  contact: {{ .Values.contact | default "9D" | quote }}
  {{ if eq .Values.infra.region "us-east-1" }}HA: true{{ end }}
  {{- if eq .Values.infra.region "us-west-1" -}}
       HA-WEST: true
  {{- end -}}
  
  {{- range $i, $val := .Values.LangUsed }}
    - {{ . | title | quote }}
  {{ end -}}
  {{- $relname := .Release.Name -}}
  {{- with .Values.tags }}
  MachineType: {{ .machine | default "NA" | quote }}
  RackID: {{ .rack | quote }}
  StorageType: {{ .drive | upper | quote }}
  Release: {{ $relname }}
  {{- end }}
